// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVnFKNiS57eGKhsG0sahLUgfK9BCt-I8w',
    appId: '1:350263195302:web:307badd152651617676667',
    messagingSenderId: '350263195302',
    projectId: 'video11-9c917',
    authDomain: 'video11-9c917.firebaseapp.com',
    storageBucket: 'video11-9c917.appspot.com',
    measurementId: 'G-H3CYP2VZEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3xrOknRNoN1p5OrEGT5Q0Y8Yk87f_QU',
    appId: '1:350263195302:android:693f41b478f8bc9d676667',
    messagingSenderId: '350263195302',
    projectId: 'video11-9c917',
    storageBucket: 'video11-9c917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQE-JD9BdGrnuWT0mBN94KOyv_BbT3xGI',
    appId: '1:350263195302:ios:e81ec4f354b9ede3676667',
    messagingSenderId: '350263195302',
    projectId: 'video11-9c917',
    storageBucket: 'video11-9c917.appspot.com',
    iosBundleId: 'com.example.video2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQE-JD9BdGrnuWT0mBN94KOyv_BbT3xGI',
    appId: '1:350263195302:ios:47ecd4cc54584284676667',
    messagingSenderId: '350263195302',
    projectId: 'video11-9c917',
    storageBucket: 'video11-9c917.appspot.com',
    iosBundleId: 'com.example.video2.RunnerTests',
  );
}
